# Generated by Django 5.2.7 on 2026-01-31 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Product Description')),
                ('category', models.TextField(max_length=255, verbose_name='Category')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2026, 1, 31, 22, 28, 18, 820219, tzinfo=datetime.timezone.utc), verbose_name='Created At')),
                ('imageUrl', models.URLField(verbose_name='Image url')),
                ('isAvailable', models.BooleanField(default=True, verbose_name='Is Available')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.TextField(max_length=255, verbose_name='Artist')),
                ('category', models.TextField(max_length=255, verbose_name='Category')),
                ('released', models.DateTimeField()),
                ('songUrl', models.URLField(verbose_name='Song url')),
                ('songName', models.TextField(max_length=255, verbose_name='Song Name')),
            ],
        ),
    ]
