# Generated by Django 5.2.7 on 2026-01-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='released',
            field=models.DateTimeField(blank=True, verbose_name='Released Date'),
        ),
    ]
