# Generated by Django 5.2.7 on 2026-01-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_songs_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='released',
            field=models.TextField(blank=True, verbose_name='Released Date'),
        ),
    ]
