# Generated by Django 5.2.7 on 2026-01-31 23:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_songs_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
