# Generated by Django 5.2.7 on 2026-01-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isAvailable',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Product Name'),
        ),
    ]
