# Generated by Django 5.2.7 on 2026-02-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_product_isavailable_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, max_length=50, null=True)),
                ('role', models.TextField(blank=True, max_length=50, null=True)),
                ('communityName', models.TextField(blank=True, max_length=50, null=True)),
                ('districtElderName', models.TextField(blank=True, max_length=50, null=True)),
                ('email', models.TextField(blank=True, max_length=50, null=True)),
                ('overseerUid', models.TextField(blank=True, max_length=50, null=True)),
                ('phone', models.TextField(blank=True, max_length=50, null=True)),
                ('province', models.TextField(blank=True, max_length=50, null=True)),
                ('profileUrl', models.TextField(blank=True, max_length=255, null=True)),
                ('surname', models.TextField(blank=True, max_length=50, null=True)),
                ('week1', models.TextField(blank=True, max_length=50, null=True)),
                ('week2', models.TextField(blank=True, max_length=50, null=True)),
                ('week3', models.TextField(blank=True, max_length=50, null=True)),
                ('week4', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
