# Generated by Django 5.2.7 on 2026-02-01 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('application_email', models.EmailField(max_length=255, verbose_name='Application Email')),
                ('contact_number', models.CharField(blank=True, max_length=50, verbose_name='Contact Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('expiry_date', models.TextField(blank=True, verbose_name='Expiry Date')),
                ('created_at', models.TextField(blank=True, verbose_name='Created At')),
                ('updated_at', models.TextField(blank=True, null=True, verbose_name='Updated At')),
                ('image_url', models.URLField(blank=True, verbose_name='Image URL')),
                ('link', models.URLField(blank=True, verbose_name='External Link')),
                ('details_address', models.TextField(blank=True, verbose_name='Details Address')),
                ('course_duration', models.CharField(blank=True, max_length=255, verbose_name='Course Duration')),
                ('duties_financial', models.TextField(blank=True, verbose_name='Duties Financial')),
                ('duties_location', models.CharField(blank=True, max_length=255, verbose_name='Duties Location')),
                ('requirements_subtitle', models.TextField(blank=True, verbose_name='Requirements Subtitle')),
                ('benefits', models.TextField(blank=True, default='[]', verbose_name='Benefits (JSON)')),
                ('required_documents', models.TextField(blank=True, default='[]', verbose_name='Required Documents (JSON)')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_elder_name', models.CharField(max_length=255, verbose_name='District Elder Name')),
            ],
        ),
        migrations.CreateModel(
            name='Overseer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True, verbose_name='Firebase UID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('overseer_initials_surname', models.CharField(max_length=255, verbose_name='Initials & Surname')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('role', models.CharField(default='overseer', max_length=50, verbose_name='Role')),
                ('subscription_status', models.CharField(default='inactive', max_length=50, verbose_name='Subscription Status')),
                ('paystack_auth_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paystack Auth Code')),
                ('paystack_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Paystack Email')),
            ],
        ),
        migrations.CreateModel(
            name='OverseerExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.TextField(blank=True, null=True, verbose_name='Archived At')),
                ('overseer_uid', models.CharField(max_length=255, verbose_name='Overseer UID')),
                ('district_elder_name', models.CharField(max_length=255, verbose_name='District Elder Name')),
                ('community_name', models.CharField(max_length=255, verbose_name='Community Name')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('expense_central', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Expense Central')),
                ('expense_other', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Expense Other')),
                ('expense_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Expense Rent')),
                ('expense_mine', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Expense Mine')),
                ('total_banked', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Banked')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Expenses')),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Income')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('poster_url', models.URLField(blank=True, verbose_name='Poster URL')),
                ('day', models.CharField(max_length=10, verbose_name='Day')),
                ('month', models.CharField(max_length=20, verbose_name='Month')),
                ('parsed_date', models.TextField(blank=True, verbose_name='Parsed Date')),
                ('created_at', models.TextField(blank=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=255, verbose_name='Community Name')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='api.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='overseer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.overseer'),
        ),
    ]
