# Generated by Django 5.2.7 on 2026-02-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_careeropportunity_district_overseer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeropportunity',
            name='expiry_date',
            field=models.TextField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='parsed_date',
            field=models.TextField(blank=True, null=True, verbose_name='Parsed Date'),
        ),
    ]
