# Generated by Django 5.2.7 on 2026-02-01 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_careeropportunity_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='UID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('name', models.CharField(max_length=255, verbose_name='First Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('portfolio', models.CharField(blank=True, max_length=255, verbose_name='Portfolio')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Province')),
                ('face_url', models.URLField(blank=True, verbose_name='Face URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.TextField(blank=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='TactsoBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='UID')),
                ('university_name', models.CharField(max_length=255, verbose_name='University Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('application_link', models.URLField(blank=True, verbose_name='Application Link')),
                ('image_url', models.URLField(blank=True, verbose_name='Image URL')),
                ('has_multiple_campuses', models.BooleanField(default=False, verbose_name='Has Multiple Campuses')),
                ('is_application_open', models.BooleanField(default=False, verbose_name='Is Application Open')),
                ('created_at', models.TextField(blank=True, verbose_name='Created At')),
            ],
        ),
        migrations.AddField(
            model_name='overseer',
            name='authorized_user_face_urls',
            field=models.TextField(blank=True, default='[]', verbose_name='Authorized Face URLs (JSON)'),
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('portfolio', models.CharField(max_length=255, verbose_name='Portfolio')),
                ('face_url', models.URLField(blank=True, verbose_name='Face URL')),
                ('added_at', models.TextField(blank=True, verbose_name='Added At')),
                ('overseer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='api.overseer')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=255, verbose_name='Campus Name')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='api.tactsobranch')),
            ],
        ),
    ]
