# Generated by Django 5.2.7 on 2026-02-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_staffmember_tactsobranch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('details', models.TextField(verbose_name='Details')),
                ('reference_id', models.CharField(blank=True, default='N/A', max_length=255, verbose_name='Reference ID')),
                ('actor_name', models.CharField(max_length=255, verbose_name='Actor Name')),
                ('actor_role', models.CharField(max_length=100, verbose_name='Actor Role')),
                ('actor_face_url', models.URLField(blank=True, verbose_name='Actor Face URL')),
                ('uid', models.CharField(max_length=255, verbose_name='User UID')),
                ('university_name', models.CharField(blank=True, max_length=255, verbose_name='University Name')),
                ('university_logo', models.URLField(blank=True, verbose_name='University Logo')),
                ('branch_email', models.EmailField(blank=True, max_length=254, verbose_name='Branch Email')),
                ('target_member_name', models.CharField(blank=True, max_length=255, verbose_name='Target Member Name')),
                ('target_member_role', models.CharField(blank=True, max_length=100, verbose_name='Target Member Role')),
                ('student_name', models.CharField(blank=True, default='N/A', max_length=255, verbose_name='Student Name')),
                ('timestamp', models.TextField(verbose_name='Timestamp')),
                ('device_time', models.CharField(blank=True, max_length=255, verbose_name='Device Time')),
            ],
        ),
    ]
