# Generated by Django 5.2.7 on 2026-02-01 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='tactsobranch',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tactsobranch',
            name='authorized_user_face_urls',
            field=models.TextField(blank=True, default='[]', verbose_name='Authorized Face URLs (JSON)'),
        ),
        migrations.AddField(
            model_name='tactsobranch',
            name='education_officer_face_url',
            field=models.URLField(blank=True, verbose_name='Education Officer Face URL'),
        ),
        migrations.AddField(
            model_name='tactsobranch',
            name='education_officer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Education Officer Name'),
        ),
        migrations.AddField(
            model_name='tactsobranch',
            name='image_urls',
            field=models.TextField(blank=True, default='[]', verbose_name='Image URLs (JSON)'),
        ),
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, verbose_name='Application UID')),
                ('user_id', models.CharField(max_length=255, verbose_name='User ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('submission_date', models.TextField(blank=True, verbose_name='Submission Date')),
                ('applying_for_funding', models.BooleanField(default=False, verbose_name='Funding')),
                ('applying_for_residence', models.BooleanField(default=False, verbose_name='Residence')),
                ('highest_qualification', models.CharField(blank=True, max_length=255, verbose_name='Qualification')),
                ('campus', models.CharField(blank=True, max_length=255, verbose_name='Campus')),
                ('primary_program', models.CharField(blank=True, max_length=255, verbose_name='Primary Program')),
                ('id_passport_url', models.URLField(blank=True, verbose_name='ID/Passport URL')),
                ('school_results_url', models.URLField(blank=True, verbose_name='School Results URL')),
                ('proof_of_registration_url', models.URLField(blank=True, verbose_name='Proof of Reg URL')),
                ('other_qualifications_url', models.URLField(blank=True, verbose_name='Other Docs URL')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.tactsobranch')),
            ],
        ),
        migrations.CreateModel(
            name='BranchCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('face_url', models.URLField(blank=True, verbose_name='Face URL')),
                ('added_at', models.TextField(blank=True, verbose_name='Added At')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='api.tactsobranch')),
            ],
        ),
    ]
