# Generated by Django 5.2.7 on 2026-02-01 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_auditlog_reference_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUniversityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_uid', models.CharField(max_length=255, verbose_name='Application UID')),
                ('university_name', models.CharField(max_length=255, verbose_name='University Name')),
                ('campus_name', models.CharField(blank=True, max_length=255, verbose_name='Campus Name')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('submission_date', models.TextField(blank=True, verbose_name='Submission Date')),
                ('primary_program', models.CharField(blank=True, max_length=255, verbose_name='Primary Program')),
                ('second_choice_program', models.CharField(blank=True, max_length=255, verbose_name='Second Choice Program')),
                ('third_choice_program', models.CharField(blank=True, max_length=255, verbose_name='Third Choice Program')),
                ('applying_for_funding', models.BooleanField(default=False, verbose_name='Funding')),
                ('applying_for_residence', models.BooleanField(default=False, verbose_name='Residence')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('highest_qualification', models.CharField(blank=True, max_length=255, verbose_name='Highest Qualification')),
                ('previous_school', models.CharField(blank=True, max_length=255, verbose_name='Previous School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_applications', to='api.users')),
            ],
        ),
    ]
