# Generated by Django 5.2.7 on 2026-02-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_useruniversityapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrequest',
            name='campus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Campus'),
        ),
    ]
