# Generated by Django 5.2.7 on 2026-02-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_community_latitude_community_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overseer',
            name='authorized_user_face_urls',
        ),
        migrations.RemoveField(
            model_name='overseer',
            name='paystack_auth_code',
        ),
        migrations.RemoveField(
            model_name='overseer',
            name='paystack_email',
        ),
        migrations.RemoveField(
            model_name='overseer',
            name='role',
        ),
        migrations.RemoveField(
            model_name='overseer',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='overseer',
            name='uid',
        ),
        migrations.AddField(
            model_name='community',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='overseer',
            name='chairperson_face_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overseer',
            name='chairperson_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='overseer',
            name='secretary_face_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overseer',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_elder_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='overseer',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='overseer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='overseer',
            name='overseer_initials_surname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='overseer',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='overseer',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
