# Generated by Django 5.2.7 on 2026-02-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_overseer_authorized_user_face_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='district_elder_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
